<?php

namespace App\Http\Requests\Api;

use Illuminate\Foundation\Http\FormRequest;

class SystemSettingUpdateRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'settings' => ['required', 'array'],
            'settings.maintenance_banner' => ['nullable', 'string', 'max:500'],
            'settings.app_name' => ['nullable', 'string', 'max:120'],
            'settings.logo_url' => ['nullable', 'string', 'max:500'],
            'settings.favicon_url' => ['nullable', 'string', 'max:500'],
            'settings.primary_color' => ['nullable', 'string', 'max:20'],
            'settings.secondary_color' => ['nullable', 'string', 'max:20'],
            'settings.email_sender_name' => ['nullable', 'string', 'max:120'],
            'settings.email_sender_address' => ['nullable', 'email', 'max:160'],
            'settings.smtp_host' => ['nullable', 'string', 'max:160'],
            'settings.smtp_port' => ['nullable', 'integer', 'min:1', 'max:65535'],
            'settings.smtp_username' => ['nullable', 'string', 'max:160'],
            'settings.smtp_password' => ['nullable', 'string', 'max:200'],
            'settings.smtp_encryption' => ['nullable', 'string', 'in:ssl,tls'],
            'settings.email_test_template' => ['nullable', 'array'],
            'settings.email_test_template.subject' => ['nullable', 'string', 'max:200'],
            'settings.email_test_template.body' => ['nullable', 'string', 'max:2000'],
            'settings.newsletter_launch_subject' => ['nullable', 'string', 'max:200'],
            'settings.newsletter_launch_body' => ['nullable', 'string', 'max:5000'],
            'settings.newsletter_launch_date' => ['nullable', 'date'],
            'settings.default_visibility' => ['nullable', 'string', 'in:public,institution_only'],
            'settings.auto_verify_alumni' => ['nullable', 'boolean'],
            'settings.require_institution_approval' => ['nullable', 'boolean'],
            'settings.max_institution_admins' => ['nullable', 'integer', 'min:1', 'max:100'],
            'settings.require_join_approval' => ['nullable', 'boolean'],
            'settings.institution_verification_required' => ['nullable', 'boolean'],
            'settings.moderation_keywords' => ['nullable', 'array'],
            'settings.moderation_keywords.*' => ['string', 'max:120'],
            'settings.report_categories' => ['nullable', 'array'],
            'settings.report_categories.*' => ['string', 'max:120'],
            'settings.moderation_auto_hide_threshold' => ['nullable', 'integer', 'min:1', 'max:100'],
            'settings.platform_fee_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'settings.platform_fee_enabled' => ['nullable', 'boolean'],
            'settings.default_currency' => ['nullable', 'string', 'max:10'],
            'settings.payout_schedule' => ['nullable', 'string', 'in:weekly,biweekly,monthly'],
            'settings.refund_window_days' => ['nullable', 'integer', 'min:0', 'max:365'],
            'settings.ads_enabled' => ['nullable', 'boolean'],
            'settings.ad_placements' => ['nullable', 'array'],
            'settings.ad_placements.*' => ['string', 'max:120'],
            'settings.default_ad_price' => ['nullable', 'numeric', 'min:0'],
            'settings.ai_enabled' => ['nullable', 'boolean'],
            'settings.ai_confidence_threshold' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'settings.ai_feed_weight' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'settings.password_min_length' => ['nullable', 'integer', 'min:6', 'max:64'],
            'settings.session_timeout_minutes' => ['nullable', 'integer', 'min:5', 'max:10080'],
            'settings.enforce_2fa' => ['nullable', 'boolean'],
            'settings.audit_log_retention_days' => ['nullable', 'integer', 'min:1', 'max:3650'],
            'settings.theme_presets' => ['nullable', 'array'],
            'settings.theme_presets.*.name' => ['required_with:settings.theme_presets', 'string', 'max:60'],
            'settings.theme_presets.*.primary' => ['nullable', 'string', 'max:20'],
            'settings.theme_presets.*.secondary' => ['nullable', 'string', 'max:20'],
            'settings.feature_flags' => ['nullable', 'array'],
            'settings.feature_flags.*' => ['string', 'max:120'],
            'settings.data_retention_days' => ['nullable', 'integer', 'min:1', 'max:3650'],
            'settings.default_moderation_rules' => ['nullable', 'array'],
            'settings.default_moderation_rules.*' => ['string', 'max:200'],
            'settings.admin_permissions' => ['nullable', 'array'],
            'settings.admin_permissions.manage_announcements' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_events' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_jobs' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_donations' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_ads' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_support_queue' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_moderation' => ['nullable', 'boolean'],
            'settings.admin_permissions.view_audit_logs' => ['nullable', 'boolean'],
            'settings.admin_permissions.view_users' => ['nullable', 'boolean'],
            'settings.admin_permissions.view_transactions' => ['nullable', 'boolean'],
            'settings.admin_permissions.manage_receipts' => ['nullable', 'boolean'],
            'settings.admin_permissions.view_subscriptions' => ['nullable', 'boolean'],
            'settings.role_catalog' => ['nullable', 'array'],
            'settings.role_catalog.*.label' => ['required_with:settings.role_catalog', 'string', 'max:120'],
            'settings.role_catalog.*.portal' => ['required_with:settings.role_catalog', 'string', 'in:admin,accounting,support'],
            'settings.role_catalog.*.permissions' => ['nullable', 'array'],
            'settings.role_catalog.*.permissions.manage_announcements' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_events' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_jobs' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_donations' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_ads' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_support_queue' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_moderation' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.view_audit_logs' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.view_users' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.view_transactions' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.manage_receipts' => ['nullable', 'boolean'],
            'settings.role_catalog.*.permissions.view_subscriptions' => ['nullable', 'boolean'],
        ];
    }
}
